/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import static Gui.Interfaz.listarticulo;
import clases.Estado;
import clases.Articulo;
import clases.Categoria;
import clases.Usuario;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author micha
 */
public class Agregar extends javax.swing.JFrame {
    String scategoria;
    String sestado;
    /**
     * Creates new form agregar
     */
    public Agregar() {
        
        
        ArrayList<Estado> estados=new ArrayList<Estado>();
        estados.add(new Estado(1,"Funcional","articulos funcionales"));
        estados.add(new Estado(2,"Malogrado","articulos malogrados"));
        estados.add(new Estado(3,"Perdido","articulos perdido"));
          
        Date fech = new Date();
        Usuario user=new Usuario("sfaeqwt4","pedro","diaz","pdiaz");
        ArrayList<Categoria> categorias=new ArrayList<Categoria>();
        categorias.add(new Categoria("1","Computadoras",fech,user));
        categorias.add(new Categoria("2","Perifericos",fech,user));
        categorias.add(new Categoria("3","Muebles",fech,user));
        initComponents();
        setLocationRelativeTo(null);
        
        
        for (Estado estado : estados) {
          combo_estado.addItem(estado.getNombre());
          
        }
        for (Categoria categoria : categorias) {
            combo_categorias.addItem(categoria.getNombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        combo_categorias = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        combo_estado = new javax.swing.JComboBox<>();
        edtdescrp = new javax.swing.JTextField();
        edtmarca = new javax.swing.JTextField();
        edtmodelo = new javax.swing.JTextField();
        edtnumeroserie = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        edtobs = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_add_arti = new javax.swing.JButton();
        jTextField5 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Descripción");

        jLabel2.setText("Marca");

        jLabel3.setText("Modelo");

        jLabel4.setText("Número de serie");

        combo_categorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        combo_categorias.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_categoriasItemStateChanged(evt);
            }
        });
        combo_categorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_categoriasActionPerformed(evt);
            }
        });

        jLabel5.setText("Observaciones");

        combo_estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar" }));
        combo_estado.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combo_estadoItemStateChanged(evt);
            }
        });
        combo_estado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_estadoActionPerformed(evt);
            }
        });

        edtdescrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edtdescrpActionPerformed(evt);
            }
        });

        edtobs.setColumns(20);
        edtobs.setRows(5);
        jScrollPane1.setViewportView(edtobs);

        jLabel7.setText("Estado");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setText("Agregar artículo");

        btn_add_arti.setText("Agregar artículo");
        btn_add_arti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_artiActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Nueva Categoria");

        jCheckBox2.setText("Selecionar Catergoría");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_add_arti))))
                        .addGap(0, 20, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6))
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox1)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(combo_categorias, 0, 102, Short.MAX_VALUE)
                            .addComponent(edtdescrp, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(edtmarca, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(edtmodelo, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(edtnumeroserie, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                            .addComponent(jTextField5)
                            .addComponent(combo_estado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edtdescrp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(edtmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(edtmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(edtnumeroserie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(combo_categorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo_estado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addComponent(btn_add_arti)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_add_artiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_artiActionPerformed
          Date fechactual = new Date();
          Usuario user=new Usuario("sfaeqwt4","pedro","diaz","pdiaz");
          Categoria categoria=new Categoria("1",scategoria,fechactual,user);
          Estado estado=new Estado(1,sestado,"nnn");
         Articulo  arti=new Articulo(1,edtdescrp.getText(),
                 fechactual,user,edtmarca.getText(),
                 edtmodelo.getText(),
                 edtnumeroserie.getText() ,
                 categoria ,fechactual,
                 edtobs.getText(),estado);
        
        //arti.add(new Articulo(1,"" ,myObj ,user,"" ,"" ,"" ,cate ,myObj,"",est));
        //  System.out.print(add);
        
   
        Interfaz In = new Interfaz();
        In.setVisible(true);
        dispose();
        Interfaz.listarticulo.add(arti);
        DefaultTableModel model = (DefaultTableModel) Interfaz.jTable2.getModel();
        Integer numid=0;
        for (Articulo articulo : listarticulo) {
            numid++;
            model.addRow(new Object[]{numid,articulo.getDescripcion().toString(),articulo.getMarca().toString(),articulo.getModelo().toString(),
            articulo.getNum_serie().toString(),articulo.getEstado().getNombre(),articulo.getCreado_el().toString(),articulo.getF_modiciacion().toString(),
            articulo.getObservaciones().toString()});
        }
        
        //model.addRow(new Object[]{1, arti.getDescripcion().toString(),arti.getMarca().toString(),arti.getModelo().toString(),
           // arti.getNum_serie().toString(),arti.getEstado().toString(),arti.getCreado_el().toString(),arti.getF_modiciacion().toString(),
           // arti.getObservaciones().toString()
        //});   
                   // TODO add your handling code here:
    }//GEN-LAST:event_btn_add_artiActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void combo_estadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_estadoActionPerformed
           
    }//GEN-LAST:event_combo_estadoActionPerformed

    private void edtdescrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edtdescrpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_edtdescrpActionPerformed

    private void combo_categoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_categoriasActionPerformed
       
    }//GEN-LAST:event_combo_categoriasActionPerformed

    private void combo_categoriasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_categoriasItemStateChanged
          if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
              scategoria=evt.getItem().toString();
            
        }
    }//GEN-LAST:event_combo_categoriasItemStateChanged

    private void combo_estadoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combo_estadoItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
              sestado=evt.getItem().toString();
            
        }
    }//GEN-LAST:event_combo_estadoItemStateChanged
  
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agregar().setVisible(true);
                 
          
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_arti;
    private javax.swing.JComboBox<String> combo_categorias;
    private javax.swing.JComboBox<String> combo_estado;
    private javax.swing.JTextField edtdescrp;
    private javax.swing.JTextField edtmarca;
    private javax.swing.JTextField edtmodelo;
    private javax.swing.JTextField edtnumeroserie;
    private javax.swing.JTextArea edtobs;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
